version: '3'
services:
  app:
    build: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/myapp
      - bundle-data:/usr/local/bundle
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
      - vendor-store:/myapp/vendor
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - node_modules-store:/myapp/node_modules
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  bundle-data:
  public-data:
  tmp-data:
  log-data:
  db-data:
  node_modules-store:
  vendor-store:
  node_modules:
